apiVersion: v1
kind: Service
metadata:
  name: mvnpro-service
spec:
  selector:
    app.kubernetes.io/name: mvnpro
  ports:
    - protocol: TCP
      port: 87
      targetPort: 8080
  type: NodePort